services:
  fitam:
    build: .  # Build the Docker image from the Dockerfile in the current directory
    volumes:
      - .:/fitam  # Mount the current directory to /fitam in the container
      - ~/.ssh:/home/developer/.ssh:ro  # mount ssh keys
    user: "${UID}:${GID}"
    stdin_open: true  # Keep STDIN open even if not attached
    tty: true         # Allocate a pseudo-TTY for the container (for command-line access)
    working_dir: /fitam # Set the working directory inside the container
    runtime: nvidia   # Use Nvidia runtime for GPU access
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Make all GPUs visible
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility  # Allow for GPU compute usage

  notebook:
    build: .  # Build the Docker image from the Dockerfile in the current directory
    volumes:
      - .:/fitam  # Mount the current directory to /fitam in the container
      - ~/.ssh:/home/developer/.ssh:ro  # mount ssh keys
    
    stdin_open: true  # Keep STDIN open even if not attached
    tty: true         # Allocate a pseudo-TTY for the container (for command-line access)
    working_dir: /fitam # Set the working directory inside the container
    runtime: nvidia   # Use Nvidia runtime for GPU access
    ports:
      - "8888:8888"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Make all GPUs visible
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility  # Allow for GPU compute usage
      - JUPYTER_TOKEN=${TOKEN}  # Set the Jupyter notebook token

    command: "jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser --notebook-dir=/fitam"  # Start Jupyter notebook
